name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [main] # Set a branch to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node.js âš™ï¸
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies ğŸ“¦
        working-directory: ./frontend
        run: npm ci

      - name: Build ğŸ”§
        working-directory: ./frontend
        run: npm run build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./frontend/out # The folder the action should deploy
          branch: gh-pages # The branch the action should deploy to
          clean: true # Automatically remove deleted files from the deployment
